config/routes.rb
RiotRadioRails::Application.routes.draw do

  devise_for :administrators, path_prefix: "admin"

  get '/admin', to: 'dashboard#show', as: 'admin_root'

  resources :administrators
  
  resources :posts

  namespace :admin do
    resources :posts
  end  

  root :to => 'posts#index'
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable

  has_many :posts       
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :administrator

  validates :title, presence: :true
  validates :body, presence: :true
  validates :slug, uniqueness: :true

  before_validation :check_for_slug

  def published?
    self.published
  end

  private

    def check_for_slug
      if !self.slug.present?
        generate_slug
      elsif self.slug.match(' ')
        generate_slug(self.slug)
      end
      return
    end

    def generate_slug(string=nil)
      if string.nil?
        string = self.title
      end
      self.slug = string.parameterize.dasherize.downcase
    end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'dashboard'
  before_filter :set_post, only: [:show, :edit, :update, :destroy]
  after_action :set_published_status, only: [:edit, :update, :new, :create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url }
      format.json { head :no_content }
    end
  end

  def set_published_status
    if params[:commit] == "Publish"
      @post.published = true
    elsif params[:commit] == "Unpublish" || params[:commit] == "Save as draft"
      @post.published = false
    end
    @post.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :excerpt, :tags, :categories, :slug)
    end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  layout 'dashboard'
  # GET /administrators
  # GET /administrators.json
  before_filter :authenticate_administrator!
  before_filter :set_administrator, only: [:show, :edit, :update, :destroy]

  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)
    if @administrator.save
      redirect_to @administrator, notice: 'Administrator was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /administrators/1
  def update
    if @administrator.update(administrator_params)
      redirect_to @administrator, notice: 'Administrator was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /administrators/1
  def destroy
    @administrator.destroy
    redirect_to administrators_url, notice: 'Administrator was successfully deleted.'
  end

  private
    
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # these are the things we can set when saving
    def administrator_params
      params.require(:administrator).permit(:email, :password, :current_password, :commit)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  layout 'dashboard'

  before_filter :authenticate_administrator!

  def show
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'application'
  before_filter :set_post, only: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(:published => true).order(:created_at).reverse
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug(params[:id])
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post], :html => { :class => "posts-form" } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control_label' %><br>
    <div class="control">
      <%= f.text_field :title %>
    </div>  
  </div>
  <div class="control-group">
    <%= f.label :slug, 'Slug (if you leave this blank it will be created for you)', :class => 'control_label' %><br>
    <div class="control">
      <%= f.text_field :slug %>
    </div>  
  </div>
  <div class="control-group">
    <%= f.label :categories, :class => 'control_label' %><br>
    <div class="control">
      <%= f.text_field :categories %>
    </div>  
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control_label' %><br>
    <div class="control">
      <%= f.text_field :tags %>
    </div>  
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control_label' %><br>
    <div class="control">
      <%= f.text_area :body, :class => 'ckeditor' %>
    </div>  
  </div>
  <div class="control-group">
    <%= f.label :excerpt, :class => 'control_label' %><br>
    <div class="control">
      <%= f.text_area :excerpt %>
    </div>  
  </div>

 
  <div>
    <%= link_to 'Cancel', admin_posts_path, :class => 'btn' %>
    <% if @post.published? %>
      <%= f.submit 'Unpublish', :class => 'btn btn-primary' %>
      <%= f.submit 'Update', :class => 'btn btn-primary' %>
    <% else %>
      <%= f.submit 'Save as draft', :class => 'btn' %>
      <%= f.submit 'Publish', :class => 'btn btn-primary' %>
    <% end %>    
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_posts_path(@post) %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<h1>Listing posts</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Excerpt</th>
      <th>Tags</th>
      <th>Categories</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.body, length: 25, omission: '...') %></td>
        <td><%= truncate(post.excerpt, length: 25, omission: '...') %></td>
        <td><%= post.tags %></td>
        <td><%= post.categories %></td>
        <td><%= link_to 'Show', admin_post_path(post) %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
        <td><%= link_to 'Destroy', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_admin_post_path %>

app/views/admin/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body.html_safe %>
</p>

<p>
  <strong>Excerpt:</strong>
  <%= @post.excerpt %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @post.tags %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @post.categories %>
</p>

<p>
  <strong>Status:</strong>
  <% if @post.published? %>
    Published
  <% else %>
    Draft
  <% end %>  
  
</p>

<%= link_to 'Edit', edit_admin_post_path(@post) %> |
<%= link_to 'Back', admin_posts_path %>

app/views/administrators/_form.html.erb
<%= form_for(@administrator, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, :class => 'control_label' %>
    <div class="control">
      <%= f.text_field :email %>
    </div>  
  </div>  

  <div class="control-group">
    <%= f.label :password, :class => 'control_label' %>
    <div class="control">
      <%= f.password_field :password %>
    </div>  
  </div>  

  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control_label' %>
    <div class="control">  
      <%= f.password_field :password_confirmation %>
    </div>  
  </div>    

  <div>
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to 'Cancel', Administrator, :class => 'btn' %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<h1>Listing administrators</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.email %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>
<p>Email</p>
<p><%= @administrator.email %></p>

<table>
   <tbody>
    <tr> 
      <td><%= link_to 'Show', @administrator %></td>
      <td><%= link_to 'Edit', edit_administrator_path(@administrator) %></td>
      <td><%= link_to 'Destroy', @administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to 'Edit', edit_administrator_path(@administrator) %> |
  <%= link_to 'Back', administrators_path %>
</div>  

app/views/dashboard/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/">Riot Radio Admin</a>
    <ul class="nav">
      <%= content_tag :li, :class => 'divider-vertical' do %>
        <%= link_to 'Home', '/' %>
      <% end %>
      <%= content_tag :li, :class => 'divider-vertical' do %>
        <%= link_to 'Admins', administrators_path %>
      <% end %>
      <%= content_tag :li, :class => 'divider-vertical' do %>
        <%= link_to 'Posts', admin_posts_path %>
      <% end %>
    </ul>
    <ul class="nav pull-right">
      <li><%= link_to 'Sign out', destroy_administrator_session_path %></li>
    </ul>
  </div>
</div>

app/views/dashboard/show.html.erb
dashboard#show

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home | Riot Radio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta property="og:type" content="blog" />
	<meta property="og:site_name" content="Riot Radio" />
	<meta property='og:url' content="http://www.riotradio.co.nz" />
	<script type="text/javascript" src="http://www.riotradio.co.nz/wp-content/plugins/lastfm-recent-tracks-widget/js/jquery.lastfm.js"></script>
	<script type="text/javascript">
		jQuery(function(){
			jQuery('.lastfm_record').mosaic({
				animation	: '',
				speed		: ,
				anchor_y : 'bottom'				});
		});
	</script>
	</head>
	<body class="home blog">

		<%= render 'shared/navigation' %>

		<div class="container">
			<%= yield %>
		</div>

	</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin | Riot Radio Rails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => "dashboard/navigation" %>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/index.html.erb
<h1>Latest posts</h1>

<% @posts.each do |post| %>

  <h3><%= post.title %></h3>

  <% if post.excerpt.present? %>
    <p><%= post.excerpt %></p>
  <% else %>
    <%= truncate(post.body.html_safe, length: 250, omission: "") %>
  <% end %>
  <%= "<a href='posts/#{post.slug}'>...more</a>".html_safe %>

<% end %>

<br>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @post.title %></h2>

<p>
  <strong>Tags:</strong>
  <%= @post.tags %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @post.categories %>
</p>

<%= @post.body.html_safe %>

<%= link_to 'Back', posts_path %>

app/views/shared/_footer.html.erb
<div id="footer" role="contentinfo">
		<div id="colophon">



			<div id="footer-widget-area" role="complementary">

				<div id="first" class="widget-area">
					<ul class="xoxo">
						<li id="meta-2" class="widget-container widget_meta"><h3 class="widget-title">Meta</h3>			<ul>
			<li><a rel="nofollow" href="http://www.riotradio.co.nz/wp-login.php?action=register">Register</a></li>			<li><a rel="nofollow" href="http://www.riotradio.co.nz/wp-login.php">Log in</a></li>
			<li><a href="http://www.riotradio.co.nz/feed/" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://www.riotradio.co.nz/comments/feed/" title="The latest comments to all posts in RSS">Comments <abbr title="Really Simple Syndication">RSS</abbr></a></li>
			<li><a href="http://wordpress.org/" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress.org</a></li>
						</ul>
</li>					</ul>
				</div><!-- #first .widget-area -->




			</div><!-- #footer-widget-area -->

			<div id="site-info">
				<a href="http://www.riotradio.co.nz/" title="Riot Radio" rel="home">
					Riot Radio				</a>
			</div><!-- #site-info -->

			<div id="site-generator">
								<a href="http://wordpress.org/"
						title="Semantic Personal Publishing Platform" rel="generator">
					Proudly powered by WordPress.				</a>
			</div><!-- #site-generator -->

		</div><!-- #colophon -->
	</div><!-- #footer -->

app/views/shared/_navigation.html.erb
<div id="wrapper" class="hfeed">
	<div id="header">
		<div id="masthead">
			<div id="branding" role="banner">
								<h1 id="site-title">
					<span>
						<a href="http://www.riotradio.co.nz/" title="Riot Radio" rel="home">Riot Radio</a>
					</span>
				</h1>
				<div id="site-description"></div>
				<h1><a href="/"><%= image_tag "rr_header.jpg" %></a><h1>

			</div><!-- #branding -->

			<div id="access" role="navigation">
			  				<div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>
								                
                <div id="navMenu">
                    <ul>
                        <li><img src="images/home.jpg" border="0"><a href="/"><span><img src="images/homeOVER.jpg" border="none" align="top" /></span></a></li>
                        
                        <li><img src="images/reviews.jpg" border="0"><a href="/category/reviews"><span><img src="/wp-content/themes/riotradio/images/reviewsOVER.jpg" border="none" align="top" /></span></a></li>
                        <li><img src="/wp-content/themes/riotradio/images/mp3s.jpg" border="0"><a href="/category/mp3s"><span><img src="/wp-content/themes/riotradio/images/mp3sOVER.jpg" border="none" align="top" /></span></a></li>
                        <li><img src="/wp-content/themes/riotradio/images/features.jpg" border="0"><a href="/features"><span><img src="/wp-content/themes/riotradio/images/featuresOVER.jpg" border="none" align="top" /></span></a></li>
                        <li><img src="/wp-content/themes/riotradio/images/about.jpg" border="0"><a href="/about"><span><img src="/wp-content/themes/riotradio/images/aboutOVER.jpg" border="none" align="top" /></span></a></li>                        
                    </ul>                    
                </div> 
                
                
			</div><!-- #access -->
		</div><!-- #masthead -->
	</div><!-- #header -->